name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.6
  geocoding: ^2.1.0
  intl: ^0.20.2
  image_picker: ^1.0.4
  firebase_storage: ^12.4.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/LogoJSA.jpg
    - assets/image/PriceList.jpeg
    - assets/image/Promo.jpeg
    - assets/image/Kalender.jpeg
    - assets/image/Riwayat.jpeg
    - assets/image/TentangKami.png
    - assets/image/Lapangan.jpg
    - assets/image/PromoEvent.jpeg