// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38df_KiJzKoENKlKhIRbZcYz6DlK6h44',
    appId: '1:102592081222:web:8a9af0d8bd6c4fdd1f0947',
    messagingSenderId: '102592081222',
    projectId: 'jsa-badminton',
    authDomain: 'jsa-badminton.firebaseapp.com',
    storageBucket: 'jsa-badminton.firebasestorage.app',
    measurementId: 'G-WCNVVY1512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzn10N8JBCG4jDV2UV02zlf0jTB_oXLSg',
    appId: '1:102592081222:android:939630f4974d41411f0947',
    messagingSenderId: '102592081222',
    projectId: 'jsa-badminton',
    storageBucket: 'jsa-badminton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6srndK7oUlZJaqXmIsrIg7Mg6MR9o410',
    appId: '1:102592081222:ios:fc55bb250dfd84731f0947',
    messagingSenderId: '102592081222',
    projectId: 'jsa-badminton',
    storageBucket: 'jsa-badminton.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6srndK7oUlZJaqXmIsrIg7Mg6MR9o410',
    appId: '1:102592081222:ios:fc55bb250dfd84731f0947',
    messagingSenderId: '102592081222',
    projectId: 'jsa-badminton',
    storageBucket: 'jsa-badminton.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA38df_KiJzKoENKlKhIRbZcYz6DlK6h44',
    appId: '1:102592081222:web:895a2e55befbd38e1f0947',
    messagingSenderId: '102592081222',
    projectId: 'jsa-badminton',
    authDomain: 'jsa-badminton.firebaseapp.com',
    storageBucket: 'jsa-badminton.firebasestorage.app',
    measurementId: 'G-6YE0KEF25M',
  );
}
